output:
  rootdir: /tmp/crawl # root directory of APK storage
scrapy:
  concurrent_requests: 1
  depth_limit: 2
  item_count: 10
  log_level: INFO
  resumation:
    enabled: true
    jobdir: ./jobdir
downloads: # can be used to enable (=true) or disable (=false) downloads of various files
  apk: true
  icon: true
