output:
  rootdir: /tmp/crawl # root directory of APK storage
input:
  package_files:
  - androzoo.txt
scrapy:
  concurrent_requests: 1
  depth_limit: 2
  item_count: 10
  log_level: INFO
  ratelimit:
    default_backoff: 10
    ok_window_duration: 30
    epsilon: 0.5
  resumation:
    enabled: true
    jobdir: ./jobdir
downloads: # can be used to enable (=true) or disable (=false) downloads of various files
  apk: true
  icon: true
sentry:
  dsn: "" # DSN from Sentry
statsd: # not fully supported
  host: localhost
  port: 8125
influxdb:
  host: localhost
  port: 8086
  username: user
  password: passwd
  database: default
  ssl: false